baseURL = "https://vasileios.github.io/dss"
languageCode = "en-US"
defaultContentLanguage = "el"

title = "Algorithmic Composition"
theme = "hugo-theme-learn"
#themesdir = "themes/"
metaDataFormat = "yaml"
#defaultContentLanguageInSubdir= true
ordersectionsby = "weight"
  
publishDir= "docs"

[params]
 themeVariant="black"


[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.el]
title = ""
weight = 1
languageName = "Ελληνικά"

[[Languages.el.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/Vasileios/dss.git"
weight = 10

[[Languages.el.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bookmark'></i> creative-coding"
identifier = "CC"
url = "https://vasileios.github.io/ac-sc"
weight = 20

# Left sidebar footer items. Use HTMl or Markdown.
[[Languages.el.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Credits"
url = "/"
weight = 30


[Languages.en]
title = "Documentation for Algorithmic Composition"
weight = 2
languageName = "English"

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/Vasileios/dss.git"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bookmark'></i> creative-coding"
identifier = "CC"
url = "https://vasileios.github.io/ac-sc"
weight = 20


